name: Build APK

on:
  push:
    branches: [ main, master, note-app ]
  pull_request:
    branches: [ main, master, note-app ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Normalize gradlew and make executable
      run: |
        sed -i 's/\r$//' gradlew
        chmod +x gradlew

    - name: Set up Android SDK (API 34)
      uses: android-actions/setup-android@v3
      with:
        packages: |
          platform-tools
          platforms;android-34
          build-tools;34.0.0

    - name: Build Debug
      run: ./gradlew :app:assembleDebug --stacktrace

    - name: Build Release (unsigned)
      run: ./gradlew :app:assembleRelease --stacktrace

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload Release APK (unsigned)
      uses: actions/upload-artifact@v4
      with:
        name: app-release-unsigned
        path: app/build/outputs/apk/release/app-release-unsigned.apk


